[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:backend]
command=java %(ENV_JAVA_OPTS)s -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar
directory=/app
autostart=true
autorestart=true
priority=20
startretries=3
startsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=SPRING_PROFILES_ACTIVE="%(ENV_SPRING_PROFILES_ACTIVE)s",SPRING_DATA_MONGODB_URI="%(ENV_SPRING_DATA_MONGODB_URI)s",MONGODB_DATABASE="%(ENV_MONGODB_DATABASE)s"
