# Development Profile
spring.config.activate.on-profile=dev

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/geststore_dev

# Logging - Más verbose en desarrollo
logging.level.root=INFO
logging.level.com.geststore=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
